Parameters:
  InstanceNameParameter:
    Description: Information about the parameter
    Type: String
    Default: paweeeu ec2
  InstanceTypeParameter:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-063d43db0594b521b
      InstanceType:  { "Ref" : "InstanceTypeParameter" }
      Tags: [{ Key: Name, Value: { "Ref": "InstanceNameParameter"}}]

